######################################################################
# Automatically generated by qmake (2.01a) Tue Mar 5 00:47:18 2013
######################################################################

QT          *= webkit
TEMPLATE     = app
TARGET       = 
DEPENDPATH  += .
INCLUDEPATH += .
MOC_DIR      = .build
OBJECTS_DIR  = .build


# Input
HEADERS += ubrowse.h
SOURCES += main.cc ubrowse.cc
