######################################################################
# Automatically generated by qmake (2.01a) Tue Mar 5 00:47:18 2013
######################################################################

QT          *= script webkit
TEMPLATE     = app
TARGET       = 
DEPENDPATH  += .
INCLUDEPATH += .
MOC_DIR      = .build
OBJECTS_DIR  = .build
LIBS        *= -ldl


# Input
HEADERS += ubrowse.h autoscroller.h gcpuprofiler.h
SOURCES += main.cc ubrowse.cc autoscroller.cc gcpuprofiler.cc
